from .usuario_viewset import UsuarioViewSet
from .tarea_viewset import TareaViewSet

from .entidad_financiera_viewset import EntidadFinancieraViewSet
from .cliente_viewset import ClienteViewSet
from .cotizacion_credito_viewset import CotizacionCreditoViewSet
from .proyecto_inmobiliario_viewset import ProyectoInmobiliarioViewSet
from .unidad_inmobiliaria_viewset import UnidadInmobiliariaViewSet
from .configuracion_viewset import ConfiguracionViewSet
from .cronograma_pago_viewset import CronogramaPagoViewSet
