# Generated by Django 5.2.8 on 2025-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("ruc", models.CharField(max_length=50)),
                ("password_hash", models.CharField(max_length=255)),
                ("nombre_completo", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("razon_social", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="tarea",
            name="descripcion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tarea",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
