# Generated by Django 5.2.8 on 2025-11-23 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entidadfinanciera_cliente_cotizacioncredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('moneda_defecto', models.CharField(blank=True, choices=[('PEN', 'PEN'), ('USD', 'USD')], max_length=3, null=True)),
                ('tipo_cambio_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('tipo_tasa_defecto', models.CharField(blank=True, choices=[('nominal', 'Nominal'), ('efectiva', 'Efectiva')], max_length=10, null=True)),
                ('capitalizacion_defecto', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10, null=True)),
                ('permite_gracia_total', models.BooleanField(blank=True, null=True)),
                ('permite_gracia_parcial', models.BooleanField(blank=True, null=True)),
                ('max_meses_gracia', models.IntegerField(blank=True, null=True)),
                ('tasa_descuento_van', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('dias_anio', models.IntegerField(blank=True, null=True)),
                ('ratio_cuota_ingreso_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('seguro_incendio_tasa', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='ProyectoInmobiliario',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=250)),
                ('distrito', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos_inmobiliarios',
            },
        ),
        migrations.CreateModel(
            name='CronogramaPago',
            fields=[
                ('id_cronograma', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('tipo_periodo', models.CharField(choices=[('gracia_total', 'Gracia Total'), ('gracia_parcial', 'Gracia Parcial'), ('normal', 'Normal')], max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amortizacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.PROTECT, related_name='cronograma', to='api.cotizacioncredito')),
            ],
            options={
                'db_table': 'cronograma_pagos',
            },
        ),
        migrations.CreateModel(
            name='UnidadInmobiliaria',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_unidad', models.CharField(choices=[('departamento', 'Departamento'), ('casa', 'Casa')], max_length=20)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_dormitorios', models.IntegerField()),
                ('num_banos', models.IntegerField()),
                ('num_estacionamientos', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_precio', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], max_length=3)),
                ('inicial_minima_porc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elegible_bono_techo_propio', models.BooleanField(blank=True, null=True)),
                ('monto_bono_disponible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('separada', 'Separada'), ('vendida', 'Vendida')], max_length=10, null=True)),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='api.proyectoinmobiliario')),
            ],
            options={
                'db_table': 'unidades_inmobiliarias',
            },
        ),
    ]
