# Generated by Django 5.2.8 on 2025-11-23 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_alter_tarea_descripcion_alter_tarea_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadFinanciera',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tasa_min', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tasa_max', models.DecimalField(decimal_places=4, max_digits=6)),
                ('plazo_min_meses', models.IntegerField()),
                ('plazo_max_meses', models.IntegerField()),
                ('permite_gracia', models.BooleanField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'entidades_financieras',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'CE'), ('PASAPORTE', 'PASAPORTE')], max_length=15)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('ocupacion', models.CharField(max_length=100)),
                ('tipo_empleo', models.CharField(choices=[('dependiente', 'Dependiente'), ('independiente', 'Independiente')], max_length=20)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deudas_actuales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_registro', models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_registrados', to='api.usuario')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='CotizacionCredito',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cotizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('id_unidad', models.IntegerField()),
                ('precio_inmueble', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_inicial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aplica_bono_techo_propio', models.BooleanField(blank=True, null=True)),
                ('monto_bono_techo_propio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_financiar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], max_length=3)),
                ('plazo_meses', models.IntegerField()),
                ('tasa_interes', models.DecimalField(decimal_places=6, max_digits=8)),
                ('tipo_tasa', models.CharField(choices=[('nominal', 'Nominal'), ('efectiva', 'Efectiva')], max_length=10)),
                ('capitalizacion', models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10, null=True)),
                ('tasa_efectiva_mensual', models.DecimalField(decimal_places=6, max_digits=8)),
                ('tasa_efectiva_anual', models.DecimalField(decimal_places=6, max_digits=8)),
                ('tiene_gracia', models.BooleanField(blank=True, null=True)),
                ('tipo_gracia', models.CharField(blank=True, choices=[('total', 'Total'), ('parcial', 'Parcial')], max_length=10, null=True)),
                ('meses_gracia', models.IntegerField(blank=True, null=True)),
                ('seguro_desgravamen', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('seguro_incendio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('comision_apertura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gastos_notariales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gastos_registrales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_con_seguros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_intereses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_total_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tcea', models.DecimalField(decimal_places=4, max_digits=8)),
                ('van_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tir_credito', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('ratio_cuota_ingreso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_cotizacion', models.DateTimeField(blank=True, null=True)),
                ('estado_cotizacion', models.CharField(blank=True, choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('presentada_banco', 'Presentada a banco'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='api.cliente')),
                ('id_usuario_asesor', models.ForeignKey(db_column='id_usuario_asesor', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_asesor', to='api.usuario')),
                ('id_entidad', models.ForeignKey(db_column='id_entidad', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='api.entidadfinanciera')),
            ],
            options={
                'db_table': 'cotizaciones_credito',
            },
        ),
    ]
